apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kddn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0062-tenant/tkrw-pr712-0075-0062-app/devfile-sample-kddn@sha256:9172467491d6c4bd166e04f59563e7bb9fcf72da51b7b69293bf18eab833743a
        name: my-nodejs
        resources: {}
status: {}
